version: '3.8'

services:
  chat-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - rentall-network

networks:
  rentall-network:
    driver: bridge
