version: '3.8'

services:
  chat-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - rentall-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

networks:
  rentall-network:
    driver: bridge
