version: '3.8'

services:
  chat-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload